/**
 * @Author Eyden Enriquez
 * @Since 2024
 * @Description: Class wich contains reusable variables
*/
public with sharing class Constants {

    public static final String USERNAME = '******';
    public static final String PASSWORD = '******';
    public static final String SECURITY_TOKEN = '******';
    public static final String CLIENT_ID = '******'; //From connected app
    public static final String CLIENT_SECRET = '******'; //From connected app
    public static final String ENDPOINT = 'https://******/services/oauth2/token';
}