/**
 * @Author Eyden Enriquez
 * @Since 2024
 * @Description: Class wich contains reusable variables
*/
public with sharing class Constants {

    public static final String USERNAME = 'edene@resourceful-badger-9pqdgs.com';
    public static final String PASSWORD = 'eydenBalink2025!';
    public static final String SECURITY_TOKEN ='1DQB2vzfFfCwgehbZL3k5CKt';
    public static final String CLIENT_ID = '3MVG9YFqzc_KnL.wqVtfZ62DzQo6T8oYRaaTSxEn9WQZbUGgT5F8WsKisX_ERqYdp46piZkoRNm5Z6gdEcH3l'; //From connected app
    public static final String CLIENT_SECRET = '1F5E2035B6C34FFF86A92D8C19E4243E456F73FB088AAB41C557F8E8D872C4D1'; //From connected app
    public static final String ENDPOINT = 'https://resourceful-badger-9pqdgs-dev-ed.trailblaze.my.salesforce.com/services/oauth2/token';
}